version: '3.9'

services:
  app:
    image: node:23
    container_name: dgpart_www_app
    ports:
      - "9800:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
