version: '3.9'

services:
  app:
    image: node:23 # Используется Node.js v23
    container_name: dgpart_www_app
    ports:
      - "9800:3000" # Пробрасываем порт для Nuxt
    volumes:
      - .:/usr/src/app # Монтируем текущую директорию
      - /usr/src/app/node_modules # Исключаем node_modules из монтирования
    working_dir: /usr/src/app # Устанавливаем рабочую директорию
    command: sh -c "npm install && npm run dev" # Установка зависимостей и запуск Nuxt
    environment:
      NODE_ENV: development # Переменная окружения для разработки
