version: '3.5'

services:

    app:
        container_name: "dgpart_front"
        image: node:14
        volumes:
            - ./:/app
        working_dir: /app
        command: ['yarn', 'run', 'dev']

    app_static:
        container_name: "dgpart_static"
        image: webdevops/nginx
        volumes:
            - ./vhost.conf:/opt/docker/etc/nginx/vhost.conf
            - ./static:/app/static
        ports:
            - ${APPPORTS}
        depends_on:
            - app
