server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp|mp4|mov)$ {
        try_files /public$uri =404;
        access_log off;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        expires off;
    }

    # Обработка .well-known для верификации
    location /.well-known/ {
        alias /usr/share/nginx/html/public/.well-known/;
        try_files $uri $uri/ =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /index.html {
        add_header 'Cache-Control' 'no-cache, no-store, must-revalidate';
        add_header 'Pragma' 'no-cache';
        add_header 'Expires' '0';
    }
}
