name: Docker Build and Publish

on:
  push:
    branches: [ "master" ] # <--- ИЗМЕНЕНО НА master

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME будет установлен в шаге ниже, чтобы гарантировать нижний регистр

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image name to lowercase
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3 # Используйте v3 для более новых версий
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build-and-push # Это задание будет выполняться только после успешной сборки и публикации образа
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read # Необходимо для скачивания образа из GHCR

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            CONTAINER_NAME="dgpart_vue"
            DOCKER_PORT_MAPPING="9800:80"
            WEB_ROOT_CONTAINER_PUBLIC="/app/public"

            # IMAGE_NAME уже доступен из предыдущего шага благодаря $GITHUB_ENV
            # REGISTRY также доступен как переменная окружения
            DOCKER_REPO_FULL="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

            echo "Deploying image: ${DOCKER_REPO_FULL}:latest"

            docker pull ${DOCKER_REPO_FULL}:latest
            docker stop ${CONTAINER_NAME} || true
            docker rm ${CONTAINER_NAME} || true

            docker run -d \
              -p ${DOCKER_PORT_MAPPING} \
              -v "${{ secrets.STATIC_DIR_HOST }}:${WEB_ROOT_CONTAINER_PUBLIC}" \
              --name ${CONTAINER_NAME} \
              ${DOCKER_REPO_FULL}:latest

            echo "Deployment successful!"